using UnityEngine;

namespace IterationRoom
{
    // Something the player can pick up with E: the balloon tool in the nightstand drawer, and the
    // key a balloon gives up.
    //
    // Range is polled rather than driven by trigger callbacks, for the reason documented on
    // FloorButton - the loop's teleport disables and re-enables the CharacterController inside one
    // frame, so an exit callback never arrives and the item would stay grabbable from across the room.
    [RequireComponent(typeof(Collider))]
    public class CarryableItem : MonoBehaviour, IInteractHintTarget
    {
        // What this counts as once carried. PlayerHand keys on it and KeyLock asks for "Key".
        public string itemId = "Tool";

        // What the HUD calls it. Separate from itemId because the id is a wire value other scripts
        // match on (KeyLock asks for "Key") and renaming it for the player's benefit would break
        // them. The readout is icons now, so this only names the slot object in the hierarchy -
        // which is still worth having when four identical Images are the alternative.
        public string displayName = "TOOL";

        // The HUD's icon for this item, generated by SceneBuilder rather than sourced.
        public Sprite icon;

        // Multiplied into the icon's colour in the readout. White for everything with a silhouette of
        // its own; a KEY COLOUR for the three keys, which share one silhouette and would otherwise be
        // three identical marks in the row. The row has to answer "which keys am I carrying" for the
        // coloured doors to be readable at all, and a key shape cannot answer it.
        public Color iconTint = Color.white;

        // `showInHand` is gone. It was a fixed per-item answer - pin always out, key always pocketed
        // - to the question "what is in the hand", and Tab makes that a live choice instead. See
        // PlayerHand.Held.

        // Whether a GHOST may carry this. ON by default: a past self can repeat anything it did,
        // and picking something up is not an exception to that. Floor pads, the drawer and balloon
        // pops already work for ghosts, so an object they can touch but not hold was the odd one
        // out. Left as a flag purely as an opt-out for a future item that must not be carried -
        // nothing currently sets it false.
        public bool ghostCarryable = true;

        // The ghost currently holding this, if any. A ghost's custody is CUSTODY, not ownership:
        // every way out of it has to land the item somewhere (socket, floor, player, origin), or an
        // object that exists exactly once in the game can be lost.
        public GhostReplayer HeldByGhost { get; private set; }

        // Optional gate. The tool sits inside the drawer, so it cannot be taken through a shut one.
        public Drawer requiresOpenDrawer;

        // Resting height once this is put down. The floor of every room is y=0, so the number is
        // the object's own half-thickness, not a room measurement - which is why it lives here and
        // not in whatever code happens to drop it.
        public float floorY = 0.06f;

        public Vector3 handLocalPosition = new Vector3(0.28f, -0.24f, 0.42f);
        public Vector3 handLocalEuler = new Vector3(12f, -8f, 18f);

        // The same again for a GHOST's grip, which has its own frame - the wrist bone - and therefore
        // its own answer. Zero is "however the anchor holds it", which is what the pin and the key
        // want: that anchor was positioned and oriented against them.
        //
        // A chess piece needs its own, and the reason is the reason handLocalEuler needs one: the set
        // is modelled Z-up, so a piece's local +Z is the way it stands. Left at identity on a wrist it
        // comes out lying along the arm.
        public Vector3 ghostLocalEuler = Vector3.zero;

        // The scale to give this while it is HELD, or zero to keep whatever it has.
        //
        // It exists because SetParent(anchor, false) keeps an item's LOCAL scale and therefore changes
        // its WORLD scale whenever the two parents differ. The pin and the key are children of unscaled
        // roots, so their local scale already is their world scale and nothing had to be said. A chess
        // piece is a child of a set scaled to 0.2026 with a local scale of 1 - lifted onto a unit-scale
        // hand anchor it became 4.94x its own size, and a knee-high king filled the screen at three and
        // a half metres tall.
        //
        // Expressed as the final local scale rather than as a multiplier, because the anchor is unscaled
        // and that makes this the item's world size in the hand - a number that can be reasoned about
        // against the 0.29m of frame it has to fit into.
        public Vector3 handLocalScale = Vector3.zero;

        public AudioSource audioSource;
        public AudioClip pickupClip;

        public bool IsCarried { get; private set; }

        // IsCarried covers "in someone's hands", ghost or player. Almost every guard below wants the
        // narrower one: a ghost-held item is still very much in play for the living player.
        public bool IsCarriedByPlayer => IsCarried && HeldByGhost == null;

        // Hidden items are out of play entirely - the key spends most of an iteration inside an
        // unburst balloon - so they must not offer a prompt or answer to E.
        //
        // An item in a ghost's hands IS available. That is not a loophole, it is the path that stops
        // ghost custody being a black hole: without it a ghost that grabs the key at t=15 locks the
        // player out of it for the rest of that iteration, every iteration, with no way back.
        public bool IsAvailable => (!IsCarried || HeldByGhost != null) && visible;

        // Free for a GHOST to take - which is stricter, because a ghost must never take something
        // out of the player's pocket or back out of a lock it has already been seated in.
        public bool IsFreeForGhost => !IsCarried && visible;

        // E here would pick this up. The drawer gate is part of the answer: prompting over a pin
        // inside a shut drawer would teach the key on the one press that does nothing.
        public bool WantsInteractHint =>
            IsAvailable && playerInRange && !AlreadyHaveOne
            && (HeldByGhost != null || requiresOpenDrawer == null || requiresOpenDrawer.IsFullyOpen);

        // The player is already carrying one of these. PlayerHand.Take refuses a second of the same
        // id - `carried` is a set of IDS, not of objects - so this has to be part of "E would do
        // something here" now that an id can be a SUPPLY. Three pins share one drawer: without this
        // the two left behind sit there offering a prompt for a press that is guaranteed to no-op,
        // which is exactly the thing the prompt is supposed never to do.
        private bool AlreadyHaveOne => hand != null && hand.Has(itemId);

        public Transform HintAnchor => transform;

        private PlayerHand hand;
        private Collider trigger;
        private bool playerInRange;
        private bool visible = true;

        private Transform originParent;
        private Vector3 originLocalPosition;
        private Quaternion originLocalRotation;
        private Vector3 originLocalScale;

        private void Awake()
        {
            trigger = GetComponent<Collider>();
            originParent = transform.parent;
            originLocalPosition = transform.localPosition;
            originLocalRotation = transform.localRotation;
            // Captured with the rest of the origin, because a held item's scale is now something that
            // can be changed and every way back out has to undo it.
            originLocalScale = transform.localScale;

            // Seeded from what the build actually left on disk rather than assumed to be true. The
            // key is saved hidden - it spends the start of every run inside an unburst balloon -
            // and a component that started out believing itself visible would offer an E prompt
            // over nothing for the frames before the loop's first reset.
            Renderer first = GetComponentInChildren<Renderer>(true);
            visible = first == null || first.enabled;
        }

        // Registered by id so a ghost's recorded carry - which knows only the id - can find this.
        private void OnEnable() => ItemRegistry.Register(this);
        private void OnDisable() => ItemRegistry.Unregister(this);

        private void FixedUpdate()
        {
            if (IsCarriedByPlayer) return;

            Collider playerCollider = PlayerLookup.Collider;
            hand = PlayerLookup.Hand;

            playerInRange = playerCollider != null
                && playerCollider.enabled
                && trigger != null
                && trigger.bounds.Intersects(playerCollider.bounds);
        }

        private void Update()
        {
            if (IsCarriedByPlayer || !playerInRange || hand == null) return;
            if (LoopManager.Instance != null && !LoopManager.Instance.AcceptsInput) return;
            // Same test the prompt gates on, for the same reason: with three pins in one drawer, E on
            // the second one would reach PlayerHand.Take and be refused there. Refusing here keeps
            // the press and the prompt agreeing about what is possible.
            if (AlreadyHaveOne) return;

            // The drawer gate is about where the item SITS, so it does not apply to one a ghost has
            // already carried out of it - the pin in a past self's hand is not inside a shut drawer.
            // IsFullyOpen, not IsOpen, so the same E press cannot both open the drawer and empty it.
            if (HeldByGhost == null && requiresOpenDrawer != null && !requiresOpenDrawer.IsFullyOpen) return;

            if (!Input.GetKeyDown(KeyCode.E)) return;

            // ONE PRESS, ONE ITEM. Every takeable thing polls E for itself, so a press inside two
            // overlapping triggers used to be taken by both - fine while nothing overlapped and no two
            // takeable things shared a place, and wrong the moment 32 chess pieces stood a square apart
            // with square-wide triggers. Play found it as "some pieces come up two or three at a time".
            //
            // Deferring to the nearest candidate rather than to whoever ran first: script execution order
            // is arbitrary, so first-wins would hand the player a piece they were not looking at. Nearest
            // is also what the prompt is drawn over, so the press and the disc agree.
            // No eye, no arbitration: fail CLOSED rather than letting the press through unarbitrated.
            // The whole point of NearestTakeable is to stop one press reaching several overlapping
            // items at once (CLAUDE.md SS1.2) - skipping the check because the eye could not be found
            // would silently reopen exactly that.
            Camera eye = hand.holdAnchor != null ? hand.holdAnchor.GetComponentInParent<Camera>() : null;
            if (eye == null || ItemRegistry.NearestTakeable(eye.transform.position) != this) return;

            hand.Take(this);
        }

        public void AttachTo(Transform anchor)
        {
            HeldByGhost = null;
            IsCarried = true;
            if (trigger != null) trigger.enabled = false;

            transform.SetParent(anchor, false);
            transform.localPosition = handLocalPosition;
            transform.localRotation = Quaternion.Euler(handLocalEuler);
            if (handLocalScale != Vector3.zero) transform.localScale = handLocalScale;
            SetVisible(true);
            PlayPickup();
        }

        // Carried by a past self. ALWAYS SHOWN, and now that is true of everything a ghost carries
        // rather than only of the one in its hand.
        //
        // The rule this serves has been in the design from the start: a ghost shows what it is
        // holding, or "who has the key" and "why did the door stop opening" have no answer. Hiding
        // the rest contradicted it - and worse than cosmetically, because IsAvailable reads
        // `visible`, so a stowed item was not merely unseen but UNTAKEABLE. A past self carrying pin
        // and key with the pin out put the key somewhere the living player could neither find nor
        // reach.
        //
        // The old justification was that the player cannot reach into a past self's pocket any more
        // than into their own. The asymmetry it missed: the player has CarriedItemsDisplay telling
        // them what is in their own pockets, and a ghost has no such readout. Showing the objects IS
        // the ghost's readout, which is why this is the fix rather than a label over its head.
        //
        // WHERE on the body is the caller's business - GhostReplayer owns the layout, because it is
        // the only thing that knows how many items there are and which one is equipped. This just
        // takes custody and poses the object.
        public void AttachToGhost(GhostReplayer ghost, Transform anchor, Vector3 localPosition)
        {
            if (ghost == null || anchor == null) return;

            HeldByGhost = ghost;
            IsCarried = true;
            // The trigger stays ON and rides the ghost, which is the whole taking-it-back mechanism:
            // walk up to the past self holding the key and press E. No new verb, no new input, and
            // ControlHintDisplay already puts its own prompt over it because WantsInteractHint is
            // driven off IsAvailable.
            if (trigger != null) trigger.enabled = true;

            transform.SetParent(anchor, false);
            // NOT handLocalPosition. Those numbers are a first-person framing - 0.28 right and 0.42
            // forward of a hold anchor slung under the player's camera - and they mean nothing on a
            // rig's bone. The anchors and this offset are the tuning points for a ghost's grip,
            // which keeps CarryableItem free of any knowledge of the skeleton.
            transform.localPosition = localPosition;
            transform.localRotation = Quaternion.Euler(ghostLocalEuler);
            // The same scale the player's hand uses. A ghost's anchors are unscaled for the same
            // reason the player's is, so without this a past self holding a chess piece would be
            // holding one five times the size of the ones on the board.
            if (handLocalScale != Vector3.zero) transform.localScale = handLocalScale;
            SetVisible(true);
        }

        // `SetGhostStowed` is gone. It hid every carried item but the equipped one, which made those
        // items untakeable as well as unseen - see AttachToGhost. A ghost now wears the lot, and
        // which one is IN THE HAND is still recorded and still gates everything a tool gates
        // (GhostReplayer.HoldingEquipped): visible and equipped became two separate questions
        // instead of one.

        // Put down where it stands, still in play. This is what a ghost's timeline running out has
        // to do with whatever it was holding - a recording made from an iteration ended at t=5
        // retires at t=5 of every iteration after it, and it must not take the key with it.
        //
        // ON THE FLOOR UNDER where it stood, not at the height it was let go from. Only the XZ of
        // the argument is used. A ghost's grip is a wrist bone about a metre up, so dropping at the
        // hand's own position left the item hanging in mid-air: a carryable has no Rigidbody, and
        // deliberately so - the loop has to be able to put every object back exactly, and a
        // simulated fall settles somewhere slightly different every time. Placing it is the same
        // answer BalloonField already gave for a key coming out of a burst balloon, which is why
        // the height now lives on the item and both paths read it.
        public void DropAt(Vector3 worldPosition)
        {
            HeldByGhost = null;
            IsCarried = false;

            transform.SetParent(originParent, true);
            transform.position = new Vector3(worldPosition.x, floorY, worldPosition.z);
            transform.localRotation = originLocalRotation;
            transform.localScale = originLocalScale;
            SetVisible(true);
            if (trigger != null) trigger.enabled = true;
        }

        // Carried but not shown - the key goes straight in a pocket.
        public void Pocket()
        {
            HeldByGhost = null;
            IsCarried = true;
            if (trigger != null) trigger.enabled = false;

            // Detached, and this only started mattering once the player could take an item off a
            // ghost. A pocketed item is not moved anywhere, so before that it simply stayed where it
            // already was; taken from a past self it would stay parented to that ghost's hand and
            // ride it round the room invisibly. A no-op on every other path.
            if (transform.parent != originParent) transform.SetParent(originParent, true);
            transform.localScale = originLocalScale;

            SetVisible(false);
            PlayPickup();
        }

        // Given up to something that keeps it: the key going into Room2's keyhole. Still IsCarried
        // as far as this component is concerned - it is out of play as a pickup, and the only way
        // back is the loop's ReturnToOrigin - but it is visible again, sitting where it was put.
        //
        // Being able to watch the key leave the player's pocket and enter the lock is the point.
        // A ghost has no pocket, so it cannot do this, and now that is something you can see on
        // screen rather than a rule written down in a file.
        public void InsertInto(Transform socket)
        {
            if (socket == null) return;

            HeldByGhost = null;
            IsCarried = true;
            if (trigger != null) trigger.enabled = false;

            transform.SetParent(socket, false);
            transform.localPosition = Vector3.zero;
            transform.localRotation = Quaternion.identity;
            transform.localScale = originLocalScale;
            SetVisible(true);
        }

        public void ReturnToOrigin()
        {
            HeldByGhost = null;
            IsCarried = false;
            if (trigger != null) trigger.enabled = true;

            transform.SetParent(originParent, false);
            transform.localPosition = originLocalPosition;
            transform.localRotation = originLocalRotation;
            transform.localScale = originLocalScale;
            SetVisible(true);
        }

        // Out of play until a balloon gives it up. Not SetActive(false): Awake has to have run for
        // originParent to be captured, and an inactive object never gets there.
        public void Hide()
        {
            SetVisible(false);
            if (trigger != null) trigger.enabled = false;
        }

        public void RevealAt(Vector3 worldPosition)
        {
            if (IsCarried) return;
            transform.position = worldPosition;
            SetVisible(true);
            if (trigger != null) trigger.enabled = true;
        }

        private void SetVisible(bool show)
        {
            visible = show;
            foreach (Renderer r in GetComponentsInChildren<Renderer>(true))
                r.enabled = show;
        }

        private void PlayPickup()
        {
            if (audioSource != null && pickupClip != null) audioSource.PlayOneShot(pickupClip);
        }
    }
}
