using UnityEngine;

namespace IterationRoom
{
    // Something the player can pick up with E: the balloon tool in the nightstand drawer, and the
    // key a balloon gives up.
    //
    // Range is polled rather than driven by trigger callbacks, for the reason documented on
    // FloorButton - the loop's teleport disables and re-enables the CharacterController inside one
    // frame, so an exit callback never arrives and the item would stay grabbable from across the room.
    [RequireComponent(typeof(Collider))]
    public class CarryableItem : MonoBehaviour, IInteractHintTarget
    {
        // What this counts as once carried. PlayerHand keys on it and KeyLock asks for "Key".
        public string itemId = "Tool";

        // What the HUD calls it. Separate from itemId because the id is a wire value other scripts
        // match on (KeyLock asks for "Key") and renaming it for the player's benefit would break
        // them. The readout is icons now, so this only names the slot object in the hierarchy -
        // which is still worth having when four identical Images are the alternative.
        public string displayName = "TOOL";

        // The HUD's icon for this item, generated by SceneBuilder rather than sourced.
        public Sprite icon;

        // Multiplied into the icon's colour in the readout. White for everything with a silhouette of
        // its own; a KEY COLOUR for the three keys, which share one silhouette and would otherwise be
        // three identical marks in the row. The row has to answer "which keys am I carrying" for the
        // coloured doors to be readable at all, and a key shape cannot answer it.
        public Color iconTint = Color.white;

        // `showInHand` is gone. It was a fixed per-item answer - pin always out, key always pocketed
        // - to the question "what is in the hand", and Tab makes that a live choice instead. See
        // PlayerHand.Held.

        // Whether a GHOST may carry this. ON by default: a past self can repeat anything it did,
        // and picking something up is not an exception to that. Floor pads, the drawer and balloon
        // pops already work for ghosts, so an object they can touch but not hold was the odd one
        // out. Left as a flag purely as an opt-out for a future item that must not be carried -
        // nothing currently sets it false.
        public bool ghostCarryable = true;

        // The ghost currently holding this, if any. A ghost's custody is CUSTODY, not ownership:
        // every way out of it has to land the item somewhere (socket, floor, player, origin), or an
        // object that exists exactly once in the game can be lost.
        public GhostReplayer HeldByGhost { get; private set; }

        // Optional gate. The tool sits inside the drawer, so it cannot be taken through a shut one.
        public Drawer requiresOpenDrawer;

        // Resting height once this is put down, **measured from the floor this object stands on**.
        // The number is the object's own half-thickness, not a room measurement - which is why it
        // lives here and not in whatever code happens to drop it.
        public float floorY = 0.06f;

        // WHICH FLOOR THAT IS. Zero for everything on the ground storey, which is why every value in
        // SceneBuilder could be written as a bare half-height for as long as the building had one
        // level.
        //
        // Cycles put a second storey under the first, and `floorY` alone cannot survive that: it was
        // compared straight against `transform.position.y`, so an object on a lower floor would fall
        // straight through it to the height of the floor above, and one carried up would refuse to
        // fall at all. Splitting the two is what makes "half a cube above my own floor" and "which
        // floor" separately true, instead of one number that silently means both.
        //
        // Set by `SceneBuilder.SetFloorBase` for a whole subtree at once rather than per item - a
        // storey is a property of where a thing is, and asking each builder to remember it is asking
        // for exactly one of them to forget.
        public float floorBaseY;

        // Where this comes to rest, in world space. Every height comparison uses this; `floorY` on
        // its own is only ever an offset.
        public float RestingY => floorBaseY + floorY;

        // HOW THIS LIES WHEN IT IS PUT DOWN, as a roll in degrees. Zero - almost everything - means
        // "however it was built", which is right for anything that stands up on its own: a cube, a
        // chess piece with its own measured tilt, an escape object on its base.
        //
        // The key needs 90. Its built pose is KeyRestRotation, bow up and standing on its blade,
        // which was chosen for a key sitting somewhere findable rather than for one that has been
        // dropped - and a key stood on end where it fell reads as PLACED on purpose. BalloonField
        // already had this fix for a key coming out of a burst balloon; the same key put down by
        // hand went on standing up, because that path restored the built rotation instead.
        public float restRoll = 0f;

        public Vector3 handLocalPosition = new Vector3(0.28f, -0.24f, 0.42f);
        public Vector3 handLocalEuler = new Vector3(12f, -8f, 18f);

        // The same again for a GHOST's grip, which has its own frame - the wrist bone - and therefore
        // its own answer. Zero is "however the anchor holds it", which is what the pin and the key
        // want: that anchor was positioned and oriented against them.
        //
        // A chess piece needs its own, and the reason is the reason handLocalEuler needs one: the set
        // is modelled Z-up, so a piece's local +Z is the way it stands. Left at identity on a wrist it
        // comes out lying along the arm.
        public Vector3 ghostLocalEuler = Vector3.zero;

        // The scale to give this while it is HELD, or zero to keep whatever it has.
        //
        // It exists because SetParent(anchor, false) keeps an item's LOCAL scale and therefore changes
        // its WORLD scale whenever the two parents differ. The pin and the key are children of unscaled
        // roots, so their local scale already is their world scale and nothing had to be said. A chess
        // piece is a child of a set scaled to 0.2026 with a local scale of 1 - lifted onto a unit-scale
        // hand anchor it became 4.94x its own size, and a knee-high king filled the screen at three and
        // a half metres tall.
        //
        // Expressed as the final local scale rather than as a multiplier, because the anchor is unscaled
        // and that makes this the item's world size in the hand - a number that can be reasoned about
        // against the 0.29m of frame it has to fit into.
        public Vector3 handLocalScale = Vector3.zero;

        // The SOLID collider that makes this thing something you walk around rather than through.
        // Optional - most carryables are small enough that walking through them never comes up, and
        // they leave it null.
        //
        // NOT A SECOND COLLIDER ON THIS OBJECT. `trigger` is whatever `GetComponent<Collider>()`
        // hands back, so a solid box added alongside the reach trigger would be a coin toss over
        // which one becomes the reach - the trap BuildKeyPlinth already documents as "scenery gets a
        // solid box, a takeable gets a trigger, and it is never both." A takeable that has to be
        // solid puts the solid one on a CHILD, and points this at it.
        //
        // Enabled exactly while the object is standing in the world on its own. Every path that puts
        // it in a hand turns it off, and for two separate reasons: in the PLAYER's hand a solid box
        // parented under the camera is a block the player's own controller shoves itself against,
        // and in a GHOST's hand it would give a past self the collider ghosts are not allowed to
        // have (CLAUDE.md SS1.7 - a ghost is something you walk through, and one that pushed the
        // player would change the recording being made against it). Off while socketed too: a cube
        // is seated by a player standing right on top of a floor recess, and a solid box appearing
        // under their feet is a shove, not a wall.
        public Collider blocker;

        public AudioSource audioSource;
        public AudioClip pickupClip;

        public bool IsCarried { get; private set; }

        // LET GO OF, as opposed to sitting where it was built. `FallingItem` reads this, and without
        // it every object that starts life above the floor falls off its own shelf the moment the
        // scene loads: the pin is in a drawer, the three escape objects are on plinths, a stacked
        // cube is on another cube. Being above floorY is not the same fact as having been dropped,
        // and the first version of the fall treated them as one.
        //
        // Only DropAt sets it. Every other way out of a hand - a socket, a pocket, the loop's rewind
        // - puts the object somewhere on purpose, and a thing placed on purpose is at rest wherever
        // it was placed.
        public bool Released { get; private set; }

        // IsCarried covers "in someone's hands", ghost or player. Almost every guard below wants the
        // narrower one: a ghost-held item is still very much in play for the living player.
        public bool IsCarriedByPlayer => IsCarried && HeldByGhost == null;

        // Hidden items are out of play entirely - the key spends most of an iteration inside an
        // unburst balloon - so they must not offer a prompt or answer to E.
        //
        // An item in a ghost's hands IS available. That is not a loophole, it is the path that stops
        // ghost custody being a black hole: without it a ghost that grabs the key at t=15 locks the
        // player out of it for the rest of that iteration, every iteration, with no way back.
        public bool IsAvailable => (!IsCarried || HeldByGhost != null) && visible;

        // Free for a GHOST to take - which is stricter, because a ghost must never take something
        // out of the player's pocket or back out of a lock it has already been seated in.
        public bool IsFreeForGhost => !IsCarried && visible;

        // E here would pick this up. The drawer gate is part of the answer: prompting over a pin
        // inside a shut drawer would teach the key on the one press that does nothing.
        // ON SCREEN is the last test rather than the first, and that ordering is load-bearing:
        // ItemRegistry.NearestTakeable asks this of EVERY registered item, and `playerInRange` is
        // false for all but the handful beside the player. See PlayerLookup.InView.
        public bool WantsInteractHint =>
            IsAvailable && playerInRange && !AlreadyHaveOne
            && (HeldByGhost != null || requiresOpenDrawer == null || requiresOpenDrawer.IsFullyOpen)
            && PlayerLookup.InView(HintAnchor);

        // The player's hands are full. PlayerHand.Take refuses outright rather than swapping, so
        // this is part of "E would do something here": prompting over an object the press cannot
        // pick up is exactly the thing a prompt is supposed never to do.
        //
        // It used to be "already carrying one of THIS id", which was the same guard against a
        // narrower pocket - three pins in one drawer, two of them offering a prompt for a press
        // guaranteed to no-op. One object at a time makes the id irrelevant: what refuses the take
        // is having anything at all.
        private bool AlreadyHaveOne => hand != null && hand.HandsFull;

        public Transform HintAnchor => transform;

        private PlayerHand hand;
        private Collider trigger;
        private bool playerInRange;
        private bool visible = true;

        private Transform originParent;
        private Vector3 originLocalPosition;
        private Quaternion originLocalRotation;
        private Vector3 originLocalScale;

        private void Awake()
        {
            trigger = GetComponent<Collider>();
            originParent = transform.parent;
            originLocalPosition = transform.localPosition;
            originLocalRotation = transform.localRotation;
            // Captured with the rest of the origin, because a held item's scale is now something that
            // can be changed and every way back out has to undo it.
            originLocalScale = transform.localScale;

            // Seeded from what the build actually left on disk rather than assumed to be true. The
            // key is saved hidden - it spends the start of every run inside an unburst balloon -
            // and a component that started out believing itself visible would offer an E prompt
            // over nothing for the frames before the loop's first reset.
            Renderer first = GetComponentInChildren<Renderer>(true);
            visible = first == null || first.enabled;
        }

        // Registered by id so a ghost's recorded carry - which knows only the id - can find this.
        private void OnEnable() => ItemRegistry.Register(this);
        private void OnDisable() => ItemRegistry.Unregister(this);

        private void FixedUpdate()
        {
            if (IsCarriedByPlayer) return;

            Collider playerCollider = PlayerLookup.Collider;
            hand = PlayerLookup.Hand;

            playerInRange = playerCollider != null
                && playerCollider.enabled
                && trigger != null
                && trigger.bounds.Intersects(playerCollider.bounds);
        }

        private void Update()
        {
            if (IsCarriedByPlayer || !playerInRange || hand == null) return;
            if (LoopManager.Instance != null && !LoopManager.Instance.AcceptsInput) return;
            // Same test the prompt gates on, for the same reason: with three pins in one drawer, E on
            // the second one would reach PlayerHand.Take and be refused there. Refusing here keeps
            // the press and the prompt agreeing about what is possible.
            if (AlreadyHaveOne) return;

            // The drawer gate is about where the item SITS, so it does not apply to one a ghost has
            // already carried out of it - the pin in a past self's hand is not inside a shut drawer.
            // IsFullyOpen, not IsOpen, so the same E press cannot both open the drawer and empty it.
            if (HeldByGhost == null && requiresOpenDrawer != null && !requiresOpenDrawer.IsFullyOpen) return;

            if (!Input.GetKeyDown(KeyCode.E)) return;

            // This press has already been spent on something else. Nearest-wins arbitration below
            // decides WHICH item, but it cannot decide HOW MANY: it is recomputed per item as each
            // Update runs, and an item taken earlier in the same frame drops out of the running, so
            // the next one down the pile becomes "nearest" and takes itself too. See
            // PlayerHand.InteractedThisFrame.
            if (hand.InteractedThisFrame) return;

            // ONE PRESS, ONE ITEM. Every takeable thing polls E for itself, so a press inside two
            // overlapping triggers used to be taken by both - fine while nothing overlapped and no two
            // takeable things shared a place, and wrong the moment 32 chess pieces stood a square apart
            // with square-wide triggers. Play found it as "some pieces come up two or three at a time".
            //
            // Deferring to the nearest candidate rather than to whoever ran first: script execution order
            // is arbitrary, so first-wins would hand the player a piece they were not looking at. Nearest
            // is also what the prompt is drawn over, so the press and the disc agree.
            // No eye, no arbitration: fail CLOSED rather than letting the press through unarbitrated.
            // The whole point of NearestTakeable is to stop one press reaching several overlapping
            // items at once (CLAUDE.md SS1.2) - skipping the check because the eye could not be found
            // would silently reopen exactly that.
            Camera eye = hand.holdAnchor != null ? hand.holdAnchor.GetComponentInParent<Camera>() : null;
            if (eye == null || ItemRegistry.NearestTakeable(eye.transform.position) != this) return;

            hand.Take(this);
        }

        public void AttachTo(Transform anchor)
        {
            HeldByGhost = null;
            IsCarried = true;
            Released = false;
            if (trigger != null) trigger.enabled = false;
            SetBlocking(false);

            transform.SetParent(anchor, false);
            transform.localPosition = handLocalPosition;
            transform.localRotation = Quaternion.Euler(handLocalEuler);
            if (handLocalScale != Vector3.zero) transform.localScale = handLocalScale;
            SetVisible(true);
            PlayPickup();
        }

        // Carried by a past self. ALWAYS SHOWN, and now that is true of everything a ghost carries
        // rather than only of the one in its hand.
        //
        // The rule this serves has been in the design from the start: a ghost shows what it is
        // holding, or "who has the key" and "why did the door stop opening" have no answer. Hiding
        // the rest contradicted it - and worse than cosmetically, because IsAvailable reads
        // `visible`, so a stowed item was not merely unseen but UNTAKEABLE. A past self carrying pin
        // and key with the pin out put the key somewhere the living player could neither find nor
        // reach.
        //
        // The old justification was that the player cannot reach into a past self's pocket any more
        // than into their own. The asymmetry it missed: the player has CarriedItemsDisplay telling
        // them what is in their own pockets, and a ghost has no such readout. Showing the objects IS
        // the ghost's readout, which is why this is the fix rather than a label over its head.
        //
        // WHERE on the body is the caller's business - GhostReplayer owns the layout, because it is
        // the only thing that knows how many items there are and which one is equipped. This just
        // takes custody and poses the object.
        public void AttachToGhost(GhostReplayer ghost, Transform anchor, Vector3 localPosition)
        {
            if (ghost == null || anchor == null) return;

            HeldByGhost = ghost;
            IsCarried = true;
            Released = false;
            // The trigger stays ON and rides the ghost, which is the whole taking-it-back mechanism:
            // walk up to the past self holding the key and press E. No new verb, no new input, and
            // ControlHintDisplay already puts its own prompt over it because WantsInteractHint is
            // driven off IsAvailable.
            if (trigger != null) trigger.enabled = true;
            SetBlocking(false);

            transform.SetParent(anchor, false);
            // NOT handLocalPosition. Those numbers are a first-person framing - 0.28 right and 0.42
            // forward of a hold anchor slung under the player's camera - and they mean nothing on a
            // rig's bone. The anchors and this offset are the tuning points for a ghost's grip,
            // which keeps CarryableItem free of any knowledge of the skeleton.
            transform.localPosition = localPosition;
            transform.localRotation = Quaternion.Euler(ghostLocalEuler);
            // The same scale the player's hand uses. A ghost's anchors are unscaled for the same
            // reason the player's is, so without this a past self holding a chess piece would be
            // holding one five times the size of the ones on the board.
            if (handLocalScale != Vector3.zero) transform.localScale = handLocalScale;
            SetVisible(true);
        }

        // `SetGhostStowed` is gone. It hid every carried item but the equipped one, which made those
        // items untakeable as well as unseen - see AttachToGhost. A ghost now wears the lot, and
        // which one is IN THE HAND is still recorded and still gates everything a tool gates
        // (GhostReplayer.HoldingEquipped): visible and equipped became two separate questions
        // instead of one.

        // Put down where it stands, still in play. This is what a ghost's timeline running out has
        // to do with whatever it was holding - a recording made from an iteration ended at t=5
        // retires at t=5 of every iteration after it, and it must not take the key with it.
        //
        // WHERE IT WAS LET GO OF, and then it falls the rest of the way. The height used to be
        // forced to floorY here - the argument's XZ and nothing else - because a carryable has no
        // Rigidbody and an object released at a ghost's wrist would otherwise hang in mid-air a
        // metre up. `FallingItem` answers that properly now: one axis, real gravity, to RestingY, and
        // deterministic in a way physics cannot be here. So this keeps the height it is given and
        // lets the fall be seen.
        //
        // Clamped at RestingY rather than trusted, because the callers are not all above the floor: a
        // ghost's timeline ending passes the item's own position, which is fine, and the player's
        // own put-down passes a point ahead of them, which could be below the object's resting
        // height on a floor recess.
        public void DropAt(Vector3 worldPosition)
        {
            HeldByGhost = null;
            IsCarried = false;
            Released = true;

            transform.SetParent(originParent, true);
            transform.position = new Vector3(worldPosition.x,
                                             Mathf.Max(worldPosition.y, RestingY),
                                             worldPosition.z);
            // Whichever way it was already facing, so a dropped thing points where the player was
            // looking - it fell out of their hand, it did not turn itself to north on the way down.
            LieDown(transform.eulerAngles.y);
            transform.localScale = originLocalScale;
            SetVisible(true);
            if (trigger != null) trigger.enabled = true;
            SetBlocking(true);
        }

        // The pose of something at rest on a floor, yawed however the caller wants it. `restRoll` 0
        // means the object stands the way it was built, which is the answer for everything that has
        // a base; anything else lays it over by that much.
        //
        // Public because a burst balloon puts its key down too, and that path picks its own yaw -
        // derived from the balloon's id, so which way a given key points is the same every iteration
        // rather than a thing that changes under the player.
        public void LieDown(float yaw)
        {
            if (Mathf.Abs(restRoll) < 0.01f) { transform.localRotation = originLocalRotation; return; }
            transform.rotation = Quaternion.Euler(0f, yaw, restRoll);
        }

        // Carried but not shown - the key goes straight in a pocket.
        public void Pocket()
        {
            HeldByGhost = null;
            IsCarried = true;
            Released = false;
            if (trigger != null) trigger.enabled = false;
            SetBlocking(false);

            // Detached, and this only started mattering once the player could take an item off a
            // ghost. A pocketed item is not moved anywhere, so before that it simply stayed where it
            // already was; taken from a past self it would stay parented to that ghost's hand and
            // ride it round the room invisibly. A no-op on every other path.
            if (transform.parent != originParent) transform.SetParent(originParent, true);
            transform.localScale = originLocalScale;

            SetVisible(false);
            PlayPickup();
        }

        // Given up to something that keeps it: the key going into Room2's keyhole. Still IsCarried
        // as far as this component is concerned - it is out of play as a pickup, and the only way
        // back is the loop's ReturnToOrigin - but it is visible again, sitting where it was put.
        //
        // Being able to watch the key leave the player's pocket and enter the lock is the point.
        // A ghost has no pocket, so it cannot do this, and now that is something you can see on
        // screen rather than a rule written down in a file.
        public void InsertInto(Transform socket)
        {
            if (socket == null) return;

            HeldByGhost = null;
            IsCarried = true;
            Released = false;
            if (trigger != null) trigger.enabled = false;
            SetBlocking(false);

            transform.SetParent(socket, false);
            transform.localPosition = Vector3.zero;
            transform.localRotation = Quaternion.identity;
            transform.localScale = originLocalScale;
            SetVisible(true);
        }

        public void ReturnToOrigin()
        {
            HeldByGhost = null;
            IsCarried = false;
            Released = false;
            if (trigger != null) trigger.enabled = true;
            SetBlocking(true);

            transform.SetParent(originParent, false);
            transform.localPosition = originLocalPosition;
            transform.localRotation = originLocalRotation;
            transform.localScale = originLocalScale;
            SetVisible(true);
        }

        // Out of play until a balloon gives it up. Not SetActive(false): Awake has to have run for
        // originParent to be captured, and an inactive object never gets there.
        public void Hide()
        {
            SetVisible(false);
            if (trigger != null) trigger.enabled = false;
            SetBlocking(false);
        }

        public void RevealAt(Vector3 worldPosition)
        {
            if (IsCarried) return;
            Released = false;
            transform.position = worldPosition;
            SetVisible(true);
            if (trigger != null) trigger.enabled = true;
            SetBlocking(true);
        }

        private void SetVisible(bool show)
        {
            visible = show;
            foreach (Renderer r in GetComponentsInChildren<Renderer>(true))
                r.enabled = show;
        }

        // Paired with SetVisible on every path: something you can see and cannot reach through, or
        // something that is neither. An out-of-play object left solid is an invisible wall.
        private void SetBlocking(bool solid)
        {
            if (blocker != null) blocker.enabled = solid;
        }

        private void PlayPickup()
        {
            if (audioSource != null && pickupClip != null) audioSource.PlayOneShot(pickupClip);
        }
    }
}
