using System.Collections;
using UnityEngine;

namespace IterationRoom
{
    // The wall panels are displays, and they boot at the start of every iteration: dark when you
    // wake, then sweeping white as you sit up. It is the visual half of the announcer's
    // "New cycle initialized" - the facility powering the cell back up around you.
    //
    // Panels come up from the floor rows first with a little scatter, rather than all together. A
    // uniform fade reads as someone turning a dimmer; a staggered one reads as separate screens
    // waking, which is the point.
    //
    // At the end of the run they stop being white surfaces and become SCREENS - see the break half
    // below, and FinalRoomSequence for what starts it.
    public class WallPanelDisplay : MonoBehaviour
    {
        public Renderer[] panels;

        public Color offColor = new Color(0.13f, 0.135f, 0.15f);
        public Color onColor = Color.white;

        // **PER-PANEL SMOOTHNESS, WHICH IS WHAT REPLACED THE WEAR MAP** (2026-08-25).
        //
        // Perfectly uniform roughness across a whole building is one of the strongest tells that a
        // surface is rendered, and the first answer to it - a tiled noise map on `_MetallicGlossMap` -
        // failed for a reason that has nothing to do with the noise: URP gives every secondary map
        // `_BaseMap`'s single UV transform, so it was locked to the grain's (5,3)-per-panel repeat and
        // read as a grid of pale squares. See `SceneBuilder.WearFloor`.
        //
        // A panelled wall does not want variation INSIDE a panel anyway. It wants panel-to-panel
        // variation, which is what a wall of separately-made displays would actually have - and that
        // has no tile to repeat, because it is one number per object.
        //
        // Kept small: this is a wall of identical units, and the point is to break the perfect match,
        // not to make some panels look dirty. +/- this much on the material's own smoothness.
        public float smoothnessJitter = 0.06f;

        public float sweepDuration = 1.4f;
        // How long a single panel takes to come up, as a fraction of the whole sweep. Larger
        // values overlap the panels more and soften the wave.
        public float panelFade = 0.22f;
        // Scatter on each panel's start time, so the wave isn't a clean straight wipe.
        public float onsetJitter = 0.12f;

        // How hard the panels blow out as a cycle collapses. Well past 1 so it clears the
        // deliberately high bloom threshold and the whole room floods.
        public float flareEmission = 7f;

        // WHAT COLOUR A BLOWN-OUT PANEL IS. White for the loop's own collapse, which is a screen
        // over-driven rather than a screen saying anything. `BeginAlarm` swaps it, because an alarm
        // that flared white would wash its own colour out at exactly the moment it is loudest.
        public Color flareTint = Color.white;

        // ---- the break ----
        //
        // At the very end of the run every panel stops being a white surface and becomes a screen
        // showing a TEST CARD - colour bars with ERROR under them. A room built entirely out of
        // displays can only say it has stopped working by having them show the thing a display
        // shows when it has nothing left to show.
        //
        // Deliberately NOT the power-down. That is the loop's signature, the cell being switched
        // off before being switched back on, and using it here would say the cycle continued.
        //
        // The card and the static are generated by SceneBuilder and set per-renderer through the
        // property block: _BaseMap for the picture and _EmissionMap for the same texture again, so
        // the bars GLOW rather than being a pattern painted on a wall and lit by the ceiling.
        public Texture2D testCard;
        public Texture2D staticNoise;
        public float cardEmission = 1.5f;
        // Noise repeats per panel. Above 1 so the grain is fine enough to read as interference
        // rather than as a blotchy texture.
        public float staticTiling = 3f;

        // Panels do NOT all turn at once - they fail one by one, spreading OUTWARDS FROM THE PLINTH
        // over this long, so the break visibly travels from the thing the player just pressed. Most
        // of each panel's turn is its distance from that origin and the rest is scatter, so the
        // wave has a direction without being a clean wipe.
        public float glitchOnset = 6.5f;
        public float glitchDistanceShare = 0.8f;
        // Every panel stutters through static on the way in. A screen that cuts straight to a clean
        // test card reads as an image being assigned; one that hashes for a fifth of a second first
        // reads as a screen losing its signal.
        public float firstStaticBurst = 0.22f;

        // Burst slots per second. THE SLOT LENGTH IS WHAT MAKES A BURST A STUTTER - at 7 a single
        // slot is 0.14s, about the length of a dropped frame. A burst hits the whole wall at once;
        // between them individual panels still hash on their own, so there is always something
        // moving and every so often everything goes at the same instant.
        public float glitchBurstRate = 7f;
        // What grows over the onset is how OFTEN the whole wall goes, not how hard. Capped well
        // short of 1 on purpose - past about a third the card is hidden more than it is seen, and
        // the thing the player is meant to be able to read stops being readable.
        public float glitchBurstDutyStart = 0.06f;
        public float glitchBurstDutyEnd = 0.32f;

        public float staticChanceCalm = 0.12f;
        public float staticChanceBurst = 0.75f;
        public float deadChanceCalm = 0.04f;
        public float deadChanceBurst = 0.18f;

        private float[] onsets;
        private float[] smoothness;
        private float baseSmoothness;
        private float powered;
        private float flare;

        // Where the collapse had got to. The ending ramps down from whatever this is rather than
        // from 1, so escaping at t=52 releases a half-built flare instead of snapping it to full
        // first and then letting go.
        public float Flare => flare;

        // Break state. `glitchTime` is seconds since the press; `convertAt` is when each panel
        // fails. Null until BeginGlitch, which doubles as the test for "is the room breaking".
        private float glitchTime;
        private float[] convertAt;

        // What Apply last actually painted. LoopManager calls SetFlare EVERY FRAME OF EVERY
        // ITERATION - not just through the collapse - and for the first fifty seconds of each one
        // the value it passes is zero, unchanged, sixty times a second. Against 370 renderers that
        // was twenty-two thousand property-block round trips per second painting nothing.
        //
        // NaN rather than 0 so the first call always lands: 0 is a legitimate value for both.
        private float paintedPowered = float.NaN;
        private float paintedFlare = float.NaN;

        private MaterialPropertyBlock block;
        // URP/Lit's albedo is _BaseColor. Setting "_Color" here would silently do nothing.
        private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
        private static readonly int EmissionId = Shader.PropertyToID("_EmissionColor");
        private static readonly int BaseMapId = Shader.PropertyToID("_BaseMap");
        private static readonly int EmissionMapId = Shader.PropertyToID("_EmissionMap");
        // The panel material tiles its plaster grain 5x3 across a face. A card left on that tiling
        // comes out as a grid of fifteen tiny test cards, so this is written per panel too.
        private static readonly int BaseMapStId = Shader.PropertyToID("_BaseMap_ST");
        private static readonly int SmoothnessId = Shader.PropertyToID("_Smoothness");

        // Lazily, not in Awake: a MaterialPropertyBlock is not serialized, so recompiling a script
        // while play mode is running nulls it without Awake ever running again, and every
        // SetPropertyBlock call after that throws. Editor-only, but that is exactly the moment it
        // bites - mid-session, while tuning something.
        private MaterialPropertyBlock Block => block ??= new MaterialPropertyBlock();

        private void Awake()
        {
            BuildOnsets();
            SetPowered(0f);
        }

        // Ordered by height so the room fills upward. Computed once: the panels never move, and a
        // stable order means the boot looks the same every iteration, which a loop should.
        private void BuildOnsets()
        {
            if (panels == null) { onsets = new float[0]; return; }

            onsets = new float[panels.Length];
            float minY = float.MaxValue, maxY = float.MinValue;
            foreach (Renderer r in panels)
            {
                if (r == null) continue;
                minY = Mathf.Min(minY, r.bounds.center.y);
                maxY = Mathf.Max(maxY, r.bounds.center.y);
            }

            float span = Mathf.Max(0.001f, maxY - minY);

            // THE INVARIANT: every onset must be <= 1 - panelFade, because PowerUpRoutine stops at
            // powered = 1 and a panel only finishes when (powered - onset) / panelFade reaches 1.
            //
            // Getting this wrong does not look like a bug, which is why it shipped. The formula was
            // height * (1 - panelFade) + jitter, so the top row could land as high as 0.90 against
            // a 0.78 ceiling - those panels froze at k = 0.45, i.e. albedo 0.506, and simply stayed
            // MID GREY for the rest of the run. Half of the top row's 66 panels, in a room whose
            // whole point is that it is white.
            //
            // The jitter is subtracted from the ramp rather than clamped off the top, so the
            // scatter survives intact at the ceiling instead of half the top row landing on exactly
            // the same onset.
            float ceiling = Mathf.Max(0f, 1f - panelFade);
            float ramp = Mathf.Max(0f, ceiling - onsetJitter);

            // **READ OFF THE MATERIAL, NOT WRITTEN DOWN.** The wall, floor and ceiling do not share a
            // smoothness, and this component is put on all three; seeding from a constant would make
            // opening the game quietly repaint two of them. Same rule `LightingTuner` follows.
            smoothness = new float[panels.Length];
            baseSmoothness = 0.85f;
            foreach (Renderer r in panels)
            {
                if (r == null || r.sharedMaterial == null) continue;
                if (r.sharedMaterial.HasProperty(SmoothnessId))
                    baseSmoothness = r.sharedMaterial.GetFloat(SmoothnessId);
                break;
            }

            Random.State previous = Random.state;
            // Fixed seed: the scatter should be arbitrary but identical on every run.
            Random.InitState(20260810);
            for (int i = 0; i < panels.Length; i++)
            {
                if (panels[i] == null) continue;
                float height = (panels[i].bounds.center.y - minY) / span;
                onsets[i] = Mathf.Clamp(height * ramp + Random.Range(-onsetJitter, onsetJitter), 0f, ceiling);
                // Clamped BELOW 1: a smoothness of exactly 1 is a mirror, and one panel in a wall
                // suddenly mirroring the room would be a worse artifact than the uniformity this is
                // breaking up.
                smoothness[i] = Mathf.Clamp(
                    baseSmoothness + Random.Range(-smoothnessJitter, smoothnessJitter), 0f, 0.97f);
            }
            Random.state = previous;
        }

        // t = 0 fully dark, 1 fully lit.
        public void SetPowered(float t)
        {
            powered = t;
            Apply();
        }

        // 0 = normal, 1 = blown out. Ramped over the last seconds of a cycle: the displays are the
        // facility tearing the room down, and they go far brighter than "on" ever is.
        public void SetFlare(float t)
        {
            flare = Mathf.Clamp01(t);
            Apply();
        }

        private void Apply()
        {
            if (panels == null || onsets == null) return;

            bool breaking = convertAt != null;
            // THE GUARD, and it lives here rather than in the setters so that Awake's first
            // SetPowered(0) still lands - `powered` starts at 0, so a setter-side guard would
            // skip it and leave every panel at the material's white instead of driving it dark.
            // The NaN sentinels are what make that work.
            //
            // While breaking, every frame genuinely differs - the pattern is time-driven - so the
            // guard deliberately does not apply.
            if (!breaking && powered == paintedPowered && flare == paintedFlare) return;
            paintedPowered = powered;
            paintedFlare = flare;

            Color flareColor = flareTint * (flare * flare * flareEmission);

            // One slot index for the whole wall, so a burst hits every panel on the same frame.
            // Per panel it would smear into continuous noise and stop reading as broken FRAMES.
            int slot = breaking ? Mathf.FloorToInt(glitchTime * glitchBurstRate) : 0;
            float k = breaking && glitchOnset > 0f ? Mathf.Clamp01(glitchTime / glitchOnset) : 0f;
            bool burst = breaking && Hash(9001, slot) < Mathf.Lerp(glitchBurstDutyStart, glitchBurstDutyEnd, k);
            float staticChance = burst ? staticChanceBurst : staticChanceCalm;
            float deadChance = burst ? deadChanceBurst : deadChanceCalm;

            for (int i = 0; i < panels.Length; i++)
            {
                if (panels[i] == null) continue;

                MaterialPropertyBlock b = Block;

                if (breaking && glitchTime >= convertAt[i])
                {
                    // Read back first here, and only here: PaintScreen's three branches each write
                    // a different subset, so a panel showing the card must not inherit the textures
                    // of whichever panel used the shared block before it.
                    panels[i].GetPropertyBlock(b);
                    PaintScreen(b, i, slot, staticChance, deadChance, burst);
                    panels[i].SetPropertyBlock(b);
                    continue;
                }

                // **CLEARED, AND WITHOUT THIS THE ROOM NEVER COMES OUT OF ERROR.**
                //
                // `Block` is one `MaterialPropertyBlock` reused for every panel of every frame, and
                // nothing emptied it. `PaintScreen` writes `_BaseMap` into it - the test card, the
                // static - and this branch only ever wrote COLOURS over the top, so the texture from
                // the last panel that failed stayed in the block and was applied to every panel that
                // had not. The breaking branch above is immune because it calls `GetPropertyBlock`
                // first, which overwrites the whole block from the renderer; this one did not.
                //
                // Play found it as room1-1 still wearing ERROR after the fall (2026-09-03) - twice,
                // because the first fix was aimed at whether `ClearBreak` was CALLED. It was called
                // every time. It cleared `convertAt`, repainted the colours, and handed every panel
                // back the same test card, because the block it painted with still had one in it.
                //
                // An override that is not set here has to be ABSENT rather than stale, so the panel
                // falls back to its material - which is the only way "not broken" can be expressed.
                b.Clear();

                float f = panelFade > 0f
                    ? Mathf.Clamp01((powered - onsets[i]) / panelFade)
                    : (powered >= onsets[i] ? 1f : 0f);

                Color albedo = Color.Lerp(offColor, onColor, Mathf.SmoothStep(0f, 1f, f));
                // The flare overrides the boot state entirely - a panel still dark from the sweep
                // shouldn't stay dark while the room is blowing out around it.
                albedo = Color.Lerp(albedo, flareTint, flare);

                b.SetColor(BaseColorId, albedo);
                b.SetColor(EmissionId, flareColor);
                // Rides along in the block that was going to be written anyway, so it costs nothing
                // extra - and it has to be written HERE rather than once at startup, because this
                // branch replaces the whole block every time it paints.
                if (smoothness != null && i < smoothness.Length) b.SetFloat(SmoothnessId, smoothness[i]);
                panels[i].SetPropertyBlock(b);
            }
        }

        // One failed panel, for one frame. Three states, and which one it is comes out of the same
        // hash the whole wall shares, so the pattern is arbitrary but identical on every run.
        private void PaintScreen(MaterialPropertyBlock b, int i, int slot,
                                 float staticChance, float deadChance, bool burst)
        {
            float age = glitchTime - convertAt[i];
            float roll = Hash(i + 977, slot);

            bool dead = roll < deadChance;
            // The switch-on stutter first, the ordinary flicker after. A panel that has just gone is
            // ALWAYS static for its first fifth of a second, whatever the hash says.
            bool hash = !dead && (age < firstStaticBurst || roll < deadChance + staticChance);

            if (dead)
            {
                // Not merely dark - the picture is gone. A black base colour kills whatever map is
                // still set on the block, so there is nothing to unset.
                b.SetColor(BaseColorId, Color.black);
                b.SetColor(EmissionId, Color.black);
                return;
            }

            if (hash && staticNoise != null)
            {
                b.SetTexture(BaseMapId, staticNoise);
                b.SetTexture(EmissionMapId, staticNoise);
                // Scrolled by the SLOT rather than by time, so the grain jumps between frames the
                // way real static does instead of sliding smoothly across the wall.
                b.SetVector(BaseMapStId, new Vector4(staticTiling, staticTiling,
                                                     Hash(i * 3 + 1, slot), Hash(i * 3 + 2, slot)));
                b.SetColor(BaseColorId, Color.white);
                b.SetColor(EmissionId, Color.white * (cardEmission * 0.7f));
                return;
            }

            if (testCard == null) return;

            b.SetTexture(BaseMapId, testCard);
            b.SetTexture(EmissionMapId, testCard);
            // Sits ONCE on the panel. During a burst the picture rolls vertically - a frame the
            // display could not hold - and settles back between them.
            float rollOffset = burst ? Hash(i * 5 + 3, slot) : 0f;
            b.SetVector(BaseMapStId, new Vector4(1f, 1f, 0f, rollOffset));
            b.SetColor(BaseColorId, Color.white);
            b.SetColor(EmissionId, Color.white * cardEmission);
        }

        // Integer hash rather than Random, and that is not a micro-optimisation: BuildOnsets is
        // careful to save and restore Random.state so the panel scatter is identical every run,
        // and pulling thousands of samples a second out of the global generator here would undo
        // exactly what that care is for.
        private static float Hash(int a, int b)
        {
            uint h = (uint)(a * 73856093) ^ (uint)(b * 19349663);
            h ^= h >> 13;
            h *= 1274126177u;
            h ^= h >> 16;
            return (h & 0xFFFFFFu) / 16777216f;
        }

        public void PowerDown()
        {
            StopAllCoroutines();
            flare = 0f;
            SetPowered(0f);
        }

        public void PowerUp()
        {
            StopAllCoroutines();
            StartCoroutine(PowerUpRoutine());
        }

        private IEnumerator PowerUpRoutine()
        {
            float elapsed = 0f;
            while (elapsed < sweepDuration)
            {
                elapsed += Time.deltaTime;
                SetPowered(elapsed / sweepDuration);
                yield return null;
            }
            SetPowered(1f);
        }

        // **BOTH AT ONCE: the ERROR card AND the alarm's colour.** Cycle 3's break wants every panel
        // in the cycle - room3-0's and room3-2N's alike - to fail and to do it in red, and the two
        // halves of that are the two things this class already knows how to do.
        //
        // The glitch is what spreads: `BeginGlitch` converts each panel to the test card in a wave
        // from the origin, and a panel that has not converted yet is still painted the ordinary way.
        // So setting the colours FIRST is what makes the wave read as red arriving rather than as two
        // unrelated effects - the panels ahead of it are red, the ones behind it are failing.
        //
        // No pulse, and that is deliberate: a card that is already flickering does not need one, and
        // the coroutine the glitch runs in is the one `BeginAlarm` would have taken.
        public void BeginAlarmGlitch(Color color, Vector3 origin, float flare)
        {
            onColor = color;
            flareTint = color;
            SetPowered(1f);
            SetFlare(flare);
            BeginGlitch(origin);
        }

        // EVERY PANEL IN THE BUILDING TURNS ONE COLOUR AND BREATHES. The facility raising an alarm,
        // which is a different statement from the two this class already makes: `SetFlare` is a
        // screen being over-driven by the loop closing, and `BeginGlitch` is a screen FAILING. This
        // is a screen being used - deliberately, by whatever is left of the facility, to say one
        // thing at once on every wall.
        //
        // Driven off unscaled time, like the glitch, so a pause menu does not stop it - and because
        // the thing it is keeping time with is a siren, which is audio and has never been scaled.
        public void BeginAlarm(Color color, float period, float low, float high)
        {
            StopAllCoroutines();
            onColor = color;
            flareTint = color;
            // Nothing is off during an alarm. `onColor` only reaches a panel that the boot sweep has
            // already lit, and this has to land on all of them at once.
            SetPowered(1f);
            StartCoroutine(AlarmRoutine(Mathf.Max(0.1f, period), low, high));
        }

        private IEnumerator AlarmRoutine(float period, float low, float high)
        {
            float t = 0f;
            while (true)
            {
                t += Time.unscaledDeltaTime;
                // Sine rather than a triangle: a siren swells and falls, and a linear ramp reads as
                // a light being switched rather than one being driven.
                float u = 0.5f - 0.5f * Mathf.Cos(t / period * 2f * Mathf.PI);
                SetFlare(Mathf.Lerp(low, high, u));
                yield return null;
            }
        }

        // Starts the break and never stops it. There is nothing after this - EndingSequence's scrim
        // comes up over a room still failing, and the scene is unloaded from under it.
        //
        // `origin` is what the failure spreads out from: the plinth, i.e. the thing the player just
        // pressed. Passing the wrong point breaks nothing, it just starts the wave somewhere that
        // means nothing.
        public void BeginGlitch(Vector3 origin)
        {
            StopAllCoroutines();
            BuildConvertOrder(origin);
            glitchTime = 0f;
            StartCoroutine(GlitchRoutine());
        }

        // **AND THE WAY BACK OUT OF IT.** `BeginGlitch` says there is nothing after it and for the
        // whole game there was not - the scrim came up over a room still failing. The ending's last
        // beat needs one exception: the player wakes in room1-1 and it has to be the room they woke
        // in a hundred times, not a wall of test cards. `convertAt` null is what `Apply` reads as
        // "not breaking", so clearing it is the whole of it.
        public void ClearBreak()
        {
            StopAllCoroutines();
            convertAt = null;
            glitchTime = 0f;
            SetFlare(0f);
            SetPowered(0f);
        }

        // **A ROOM THAT BROKE A WHILE AGO**, rather than one breaking now.
        //
        // `BeginGlitch` starts the wave at zero and spreads it over `glitchOnset`; this starts it
        // already finished. Every panel is past its `convertAt`, so all of them show the test card
        // from the first frame, and the burst flicker goes on running at its settled rate - the
        // room is still failing, it is just not failing FOR you.
        //
        // Used by `FacilityExterior.Reveal`: by the time the cable car climbs past them, cycles 1
        // and 2 broke long ago and their walls should say so. Time is set past the wave rather than
        // clamped, because `PaintScreen` reads `glitchTime - convertAt[i]` only to decide whether a
        // panel is in its first fifth of a second, and `glitchOnset` saturates the burst duty at 1.
        public void ShowAlreadyBroken(Vector3 origin)
        {
            StopAllCoroutines();
            BuildConvertOrder(origin);
            glitchTime = Mathf.Max(1f, glitchOnset) * 4f;
            StartCoroutine(GlitchRoutine());
        }

        private void BuildConvertOrder(Vector3 origin)
        {
            int count = panels != null ? panels.Length : 0;
            convertAt = new float[count];
            if (count == 0) return;

            float maxDist = 0.001f;
            var dist = new float[count];
            for (int i = 0; i < count; i++)
            {
                if (panels[i] == null) continue;
                dist[i] = Vector3.Distance(panels[i].bounds.center, origin);
                maxDist = Mathf.Max(maxDist, dist[i]);
            }

            float scatterShare = Mathf.Max(0f, 1f - glitchDistanceShare);
            for (int i = 0; i < count; i++)
                convertAt[i] = glitchOnset * (dist[i] / maxDist * glitchDistanceShare
                                              + Hash(i, 4242) * scatterShare);
        }

        private IEnumerator GlitchRoutine()
        {
            while (true)
            {
                // Unscaled: the ending must not be freezable, and Apply has to run every frame or
                // the resample never lands on screen.
                glitchTime += Time.unscaledDeltaTime;
                Apply();
                yield return null;
            }
        }
    }
}
